# Generated by Django 5.0 on 2026-04-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recipiient',
            new_name='recipient',
        ),
    ]
